{
  "timestamp": "20250712_204813",
  "training_type": "walk_forward",
  "config": {
    "train_months": 3,
    "test_months": 1,
    "step_months": 1,
    "min_training_samples": 5000
  },
  "total_time_minutes": 16.93489903608958,
  "symbols_trained": 0,
  "symbols_failed": 1,
  "total_windows": 0,
  "results_by_symbol": {
    "BTCEUR": {
      "error": "Unable to train LSTM model - all batch sizes failed. Last error: Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"/notebooks/bot/train_hybrid_models.py\", line 1427, in <module>\n\n  File \"/notebooks/bot/train_hybrid_models.py\", line 1417, in main\n\n  File \"/notebooks/bot/train_hybrid_models.py\", line 1252, in train_all_models\n\n  File \"/notebooks/bot/train_hybrid_models.py\", line 1120, in train_symbol_walkforward\n\n  File \"/notebooks/bot/train_hybrid_models.py\", line 612, in train_lstm_model\n\n  File \"/usr/local/lib/python3.11/dist-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/usr/local/lib/python3.11/dist-packages/keras/src/engine/training.py\", line 1807, in fit\n\n  File \"/usr/local/lib/python3.11/dist-packages/keras/src/engine/training.py\", line 1401, in train_function\n\n  File \"/usr/local/lib/python3.11/dist-packages/keras/src/engine/training.py\", line 1384, in step_function\n\nFailed to get module function:CUDA_ERROR_OUT_OF_MEMORY: out of memory\n\t [[{{node StatefulPartitionedCall}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_train_function_163969]"
    }
  }
}